trigger:
- master
# Only run this pipeline on a Pull Request if this file is modified; the rest
# is all for azure-pipelines-linux to handle.
pr:
  branches:
    include:
    - master
  paths:
    include:
    - azure-pipelines-windows.yml

jobs:
- job: WindowsDependencies
  displayName: 'Windows Dependencies'
  pool:
    vmImage: 'windows-2019'

  strategy:
    matrix:
      Win32:
        TargetArch: 'x86'
        TargetTriplet: 'x86-windows'
      Win64:
        TargetArch: 'x64'
        TargetTriplet: 'x64-windows'

  steps:
  - script: |
      cd /d c:\vcpkg
      git pull
      .\bootstrap-vcpkg.bat
    displayName: 'Update vcpkg'
  - script: vcpkg.exe install sdl2:$(TargetTriplet) spdlog:$(TargetTriplet) entt:$(TargetTriplet) glm:$(TargetTriplet) spirv-cross:$(TargetTriplet) spirv-tools:$(TargetTriplet) bullet3:$(TargetTriplet) cxxopts:$(TargetTriplet)
    displayName: 'Install dependencies'
  - bash: |
      set -ex

      rm -rf /c/vcpkg/.git*
      rm -rf /c/vcpkg/buildtrees
      rm -rf /c/vcpkg/docs
      rm -rf /c/vcpkg/downloads
      rm -rf /c/vcpkg/packages
      rm -rf /c/vcpkg/ports
      rm -rf /c/vcpkg/toolsrc
      mv /c/vcpkg windows-dependencies
    displayName: 'Remove unused files'
  - task: ArchiveFiles@2
    displayName: Archive
    inputs:
      rootFolderOrFile: 'windows-dependencies'
      archiveType: '7z'
      archiveFile: 'windows-dependencies-$(TargetArch).7z'

  # Only publish when it triggered on 'master' (and not on a Pull Request)
  - task: PublishBuildArtifacts@1
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: Publish
    inputs:
      PathtoPublish: windows-dependencies-$(TargetArch).7z
      ArtifactName: 'windows-dependencies-$(TargetArch)'
